run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: "1.25"

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  errcheck:
    check-type-assertions: false
    check-blank: false
  gofmt:
    simplify: true
  gosec:
    severity: "medium"
    confidence: "medium"
    excludes:
      - G104 # Defer closed response/file error checks
      - G301 # Expect directory permissions to be 0750 or less
      - G304 # File inclusion via variable
      - G306 # Expect WriteFile permissions to be 0600 or less
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gofmt
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - bodyclose
    - copyloopvar

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
