#!/usr/bin/env bash
# ==============================================================================
# ☀️ SOLARIA: Interactive Setup & Deployment Wizard (Pure Go Edition)
# ==============================================================================
set -e

GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

clear || true
echo -e "${CYAN}======================================================================${NC}"
echo -e "${YELLOW}   ☀️  SOLARIA: Renogy Solar & Atmospheric Intelligence Platform       ${NC}"
echo -e "${CYAN}======================================================================${NC}"
echo -e "This wizard configures your environment, site coordinates, solar array"
echo -e "specifications, Google Cloud BigQuery pipeline, and Go edge bridge.\n"

# ------------------------------------------------------------------------------
# 1. Dependency Checks
# ------------------------------------------------------------------------------
echo -e "${CYAN}[1/5] Checking System Prerequisites...${NC}"

has_go=false
has_gcloud=false

if command -v go &>/dev/null || [ -f "$HOME/.local/go/bin/go" ]; then
    export PATH="$HOME/.local/go/bin:$PATH"
    go_ver=$(go version 2>&1)
    echo -e "  ${GREEN}✓${NC} Go: ${go_ver}"
    has_go=true
else
    echo -e "  ${RED}✗${NC} Go 1.21+ not found."
fi

if command -v gcloud &>/dev/null; then
    gcloud_acc=$(gcloud config get-value account 2>/dev/null || echo "not logged in")
    echo -e "  ${GREEN}✓${NC} Google Cloud SDK (Account: ${gcloud_acc})"
    has_gcloud=true
else
    echo -e "  ${YELLOW}!${NC} gcloud SDK not found. Cloud Run deployment requires gcloud."
fi

echo ""

# ------------------------------------------------------------------------------
# 2. Interactive Site & Solar Configuration
# ------------------------------------------------------------------------------
echo -e "${CYAN}[2/5] Configuring Solar Site & Location...${NC}"

# Read existing .env if present for smart defaults
if [ -f .env ]; then
    # shellcheck disable=SC1091
    source .env 2>/dev/null || true
fi

DEFAULT_SITE_NAME="${SITE_NAME:-1296 Wren Lake Drive, Dorset, ON}"
read -rp "  📍 Site Name / Description [$DEFAULT_SITE_NAME]: " INPUT_SITE_NAME
SITE_NAME="${INPUT_SITE_NAME:-$DEFAULT_SITE_NAME}"

DEFAULT_LAT="${SITE_LATITUDE:-45.186}"
read -rp "  🌐 Site Latitude [$DEFAULT_LAT]: " INPUT_LAT
SITE_LATITUDE="${INPUT_LAT:-$DEFAULT_LAT}"

DEFAULT_LON="${SITE_LONGITUDE:--78.863}"
read -rp "  🌐 Site Longitude [$DEFAULT_LON]: " INPUT_LON
SITE_LONGITUDE="${INPUT_LON:-$DEFAULT_LON}"

DEFAULT_WATTS="${PANEL_RATED_WATTS:-400.0}"
read -rp "  ⚡ Array Peak Capacity in Watts (e.g., 400 for 4x100W) [$DEFAULT_WATTS]: " INPUT_WATTS
PANEL_RATED_WATTS="${INPUT_WATTS:-$DEFAULT_WATTS}"

echo ""

# ------------------------------------------------------------------------------
# 3. Cloud & Security Configuration
# ------------------------------------------------------------------------------
echo -e "${CYAN}[3/5] Configuring Google Cloud Platform & Security...${NC}"

DEFAULT_PROJECT="${GCP_PROJECT:-solaria-solar}"
read -rp "  ☁️ GCP Project ID [$DEFAULT_PROJECT]: " INPUT_PROJECT
GCP_PROJECT="${INPUT_PROJECT:-$DEFAULT_PROJECT}"

DEFAULT_DATASET="${BIGQUERY_DATASET:-solaria}"
read -rp "  🗄️ BigQuery Dataset Name [$DEFAULT_DATASET]: " INPUT_DATASET
BIGQUERY_DATASET="${INPUT_DATASET:-$DEFAULT_DATASET}"

DEFAULT_TABLE="${BIGQUERY_TABLE:-telemetry}"
read -rp "  📊 BigQuery Table Name [$DEFAULT_TABLE]: " INPUT_TABLE
BIGQUERY_TABLE="${INPUT_TABLE:-$DEFAULT_TABLE}"

DEFAULT_TOKEN="${SOLARIA_API_TOKEN:-solaria_cottage_secret_token_2026}"
read -rp "  🔑 Ingestion API Auth Token [$DEFAULT_TOKEN]: " INPUT_TOKEN
SOLARIA_API_TOKEN="${INPUT_TOKEN:-$DEFAULT_TOKEN}"

DEFAULT_ENDPOINT="${SOLARIA_CLOUD_ENDPOINT:-https://solaria-dashboard-952659886764.us-central1.run.app/api/v1/telemetry}"
read -rp "  🚀 Ingestion Cloud Endpoint [$DEFAULT_ENDPOINT]: " INPUT_ENDPOINT
SOLARIA_CLOUD_ENDPOINT="${INPUT_ENDPOINT:-$DEFAULT_ENDPOINT}"

echo ""

# ------------------------------------------------------------------------------
# 4. Write Configuration to .env
# ------------------------------------------------------------------------------
echo -e "${CYAN}[4/5] Saving Configuration to .env...${NC}"

cat << ENV_EOF > .env
# ==============================================================================
# Solaria Configuration File (Auto-generated by setup.sh)
# ==============================================================================

# Google Cloud Platform
GCP_PROJECT=${GCP_PROJECT}
BIGQUERY_DATASET=${BIGQUERY_DATASET}
BIGQUERY_TABLE=${BIGQUERY_TABLE}
PORT=8080

# Site & Physical Solar Setup
SITE_NAME="${SITE_NAME}"
SITE_LATITUDE=${SITE_LATITUDE}
SITE_LONGITUDE=${SITE_LONGITUDE}
PANEL_RATED_WATTS=${PANEL_RATED_WATTS}

# Ingestion Security & Cloud Ingest URL
SOLARIA_API_TOKEN=${SOLARIA_API_TOKEN}
SOLARIA_CLOUD_ENDPOINT=${SOLARIA_CLOUD_ENDPOINT}
ENV_EOF

echo -e "  ${GREEN}✓${NC} Configuration saved to ${CYAN}.env${NC}"
echo ""

# ------------------------------------------------------------------------------
# 5. Build & Launch Options
# ------------------------------------------------------------------------------
echo -e "${CYAN}[5/5] Deployment & Launch Options:${NC}"
echo -e "  1) Build & Start Go Gateway Bridge (${CYAN}go run ./cmd/bridge${NC})"
echo -e "  2) Deploy Go Cloud Dashboard to Google Cloud Run"
echo -e "  3) Build all binaries (${CYAN}make all${NC})"
echo -e "  4) Exit setup"

read -rp "  Select an option [1-4, default: 1]: " OPTION
OPTION="${OPTION:-1}"

case "$OPTION" in
    1)
        echo -e "\n${GREEN}🚀 Starting Solaria Go Bridge...${NC}"
        go run ./cmd/bridge
        ;;
    2)
        if [ "$has_gcloud" = true ]; then
            echo -e "\n${GREEN}🚀 Deploying to Cloud Run in project ${GCP_PROJECT}...${NC}"
            gcloud config set project "$GCP_PROJECT"
            gcloud run deploy solaria-dashboard \
                --source . \
                --region us-central1 \
                --allow-unauthenticated \
                --set-env-vars "GCP_PROJECT=${GCP_PROJECT},SOLARIA_API_TOKEN=${SOLARIA_API_TOKEN}"
        else
            echo -e "\n${RED}gcloud CLI is required to deploy to Cloud Run.${NC}"
        fi
        ;;
    3)
        echo -e "\n${GREEN}🔨 Building all Go binaries...${NC}"
        make all
        echo -e "${GREEN}✓ Binaries built in bin/${NC}"
        ;;
    *)
        echo -e "\n${GREEN}Setup complete! You can run './setup.sh' at any time.${NC}"
        ;;
esac
